title: Game Dev Doc
description: A comprehensive guide covering all aspects of game development, from design to deployment.
theme: just-the-docs
color_scheme: dark
url: "https://mehendysis.github.io/GameDevelopment/"
baseurl: "/GameDevelopment"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  # Add more pages as needed with proper titles and nav_order for sorting
  # - title: Level Designer
  #   url: /docs/level-designer/
  #   nav_order: 2
  # Uncomment and add more sections if necessary
  # - title: Art Department
  #   children:
  #     - title: 2D
  #       children:
  #         - title: Concept Artist
  #           url: /docs/concept-artist/
  #           nav_order: 1
  #         - title: Texture Material Artist
  #           url: /docs/texture-material-artist/
  #           nav_order: 2
  #       nav_order: 1
  #     - title: 3D
  #       children:
  #         - title: Character Artist
  #           url: /docs/character-artist/
  #           nav_order: 1
  #         - title: Prop Artist
  #           url: /docs/prop-artist/
  #           nav_order: 2
  #       nav_order: 2
  #     - title: Animations
  #       children:
  #         - title: Animator
  #           url: /docs/animator/
  #           nav_order: 1
  #         - title: FX Artist
  #           url: /docs/fx-artist/
  #           nav_order: 2
  #       nav_order: 3
  #     - title: Audio
  #       children:
  #         - title: Sound Designer
  #           url: /docs/sound-designer/
  #           nav_order: 1
  #         - title: Compositor
  #           url: /docs/compositor/
  #           nav_order: 2
  #       nav_order: 4
  # - title: Programming Department
  #   children:
  #     - title: Game/Gameplay Programmer
  #       url: /docs/game-gameplay-programmer/
  #       nav_order: 1
  #     - title: AI Programmer
  #       url: /docs/ai-programmer/
  #       nav_order: 2
  #     - title: Shader Programmer
  #       url: /docs/shader-programmer/
  #       nav_order: 3
  #   nav_order: 5

#nav_external_links:
#  twitter: https://x.com/mehendysis
#  github: https://github.com/RallardM
#  facebook: https://www.facebook.com/Mehendysis/
#  instagram: https://www.instagram.com/mehendysis/
#  youtube: https://www.youtube.com/@Dreaven.Mehendysis
#  twitch: https://www.twitch.tv/thedreavens
#  tiktok: https://www.tiktok.com/@dreavenmehendysis
#  patreon: https://www.patreon.com/Mehendysis
#  discord: https://discord.gg/DWA87gV

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# Show navigation error report
nav_error_report: true # default is false/nil.

liquid:
  error_mode: strict
  strict_filters: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

footer_content: 'Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a> <a href="https://www.netlify.com/">This site is powered by Netlify.</a>'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all