title: Game Development Documentation
description: A comprehensive guide covering all aspects of game development, from design to deployment.
theme: just-the-docs

url: https://mehendysis.github.io/GameDevelopment/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
